# Generated by Django 5.2.1 on 2025-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelrestapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
