# Generated by Django 5.2.1 on 2025-06-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelrestapi', '0005_tourpackage_itinerarydetails_hoteldetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='titile',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='price',
        ),
    ]
