# Generated by Django 5.2.1 on 2025-06-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelrestapi', '0006_rename_titile_tourpackage_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarydetails',
            options={'ordering': ['tour_package', 'day_number'], 'verbose_name': 'Itinerary Day', 'verbose_name_plural': 'Itinerary Days'},
        ),
        migrations.AlterField(
            model_name='itinerarydetails',
            name='description',
            field=models.TextField(help_text='Use the bullet point symbol (●) at the beginning of each new point for proper formatting in the frontend.'),
        ),
    ]
